IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'RETURN_CATEGORIES')
	DROP PROC RETURN_CATEGORIES;

GO
CREATE PROCEDURE RETURN_CATEGORIES
	
AS
BEGIN
	SELECT * FROM  ICATEGORIES
END;
GO

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'RETURN_SUBCATEGORIES')
	DROP PROC RETURN_SUBCATEGORIES;

GO
CREATE PROCEDURE RETURN_SUBCATEGORIES
@CATEGORY INT
AS
BEGIN
	SELECT SUBCATEGORIEID,FIRSTCODE,LASTCODE,SUBCATEGORYNAME FROM SUBCATEGORIES WHERE CATEGORYID=@CATEGORY
END;
GO

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'RETURN_DISEASES')
	DROP PROC RETURN_DISEASES;

GO
CREATE PROCEDURE RETURN_DISEASES
@SUBCATEGORY INT	
AS
BEGIN
	SELECT DISEASEID,CODE,DISEASENAME FROM DISEASES WHERE SUBCATEGORYID=@SUBCATEGORY
END;
