IF EXISTS (SELECT * FROM sys.objects WHERE name = 'ROLES')
BEGIN
	DROP TABLE [dbo].[ROLES]
END
GO
CREATE TABLE [dbo].[ROLES](
	[IDRoles] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_dbo.ROLES] PRIMARY KEY CLUSTERED 
(
	[IDRoles] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
