IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_DOCTOR_SCHEDULE_BOOKED')
DROP PROC GET_DOCTOR_SCHEDULE_BOOKED

GO
CREATE PROCEDURE GET_DOCTOR_SCHEDULE_BOOKED
    @IDDOCTOR INT
AS
BEGIN
	SELECT IDPATIENT, START_DATETIME, END_DATETIME FROM SCHEDULE
	WHERE @IDDOCTOR=@IDDOCTOR;
END;
