IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_SCHEDULE_BY_USER_ID')
	DROP PROC GET_SCHEDULE_BY_USER_ID

GO
CREATE PROC GET_SCHEDULE_BY_USER_ID @USER_ID INT AS
BEGIN
SELECT * FROM SCHEDULE WHERE IDPATIENT = @USER_ID
END;