INSERT BLOOD_TYPES(BLOOD_TYPE) VALUES ('O-');
INSERT BLOOD_TYPES(BLOOD_TYPE) VALUES ('O+');
INSERT BLOOD_TYPES(BLOOD_TYPE) VALUES ('A-');
INSERT BLOOD_TYPES(BLOOD_TYPE) VALUES ('A+');
INSERT BLOOD_TYPES(BLOOD_TYPE) VALUES ('B-');
INSERT BLOOD_TYPES(BLOOD_TYPE) VALUES ('B+');
INSERT BLOOD_TYPES(BLOOD_TYPE) VALUES ('AB-');
INSERT BLOOD_TYPES(BLOOD_TYPE) VALUES ('AB+');