IF ((SELECT COUNT(*) FROM ALLERGIES) != 0)
	DELETE FROM ALLERGIES WHERE 1=1;

EXEC INSERT_NEW_ALLERGY_NAME_AND_ALLERGY_DESCRIPTION 'ALLERGY1','';
EXEC INSERT_NEW_ALLERGY_NAME_AND_ALLERGY_DESCRIPTION 'ALLERGY2','DESCRIPTION2';
EXEC INSERT_NEW_ALLERGY_NAME_AND_ALLERGY_DESCRIPTION 'ALLERGY3','DESCRIPTION3';
EXEC INSERT_NEW_ALLERGY_NAME_AND_ALLERGY_DESCRIPTION 'ALLERGY4','DESCRIPTION4';