IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'MEDICAL_CARD') 
	BEGIN 
		DROP TABLE MEDICAL_CARD
	END


	BEGIN
		CREATE TABLE MEDICAL_CARD (
			ID INT IDENTITY(1,1) PRIMARY KEY,
			ID_VISIT INT NOT NULL UNIQUE FOREIGN KEY REFERENCES SCHEDULE(ID),
			ID_DISEASE INT FOREIGN KEY REFERENCES SUBDISEASES(SUBDISEASEID),
			DESCRIPTION NVARCHAR(1000),
			CURE NVARCHAR(500)
		)
		END;