IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'INSERT_NEW_ALLERGY_NAME_AND_ALLERGY_DESCRIPTION')
	DROP PROC INSERT_NEW_ALLERGY_NAME_AND_ALLERGY_DESCRIPTION

	GO
	CREATE PROCEDURE INSERT_NEW_ALLERGY_NAME_AND_ALLERGY_DESCRIPTION @ALLERGY_NAME NVARCHAR(50), @ALLERGY_DESCRIPTIONS NVARCHAR(300)
	AS
	BEGIN
		IF((SELECT COUNT(ID_ALLERGY) FROM ALLERGIES) != 0) INSERT INTO ALLERGIES(ID_ALLERGY,ALLERGY_NAME,ALLERGY_DESCRIPTION) VALUES ((SELECT MAX(ID_ALLERGY) + 1 FROM ALLERGIES), @ALLERGY_NAME, @ALLERGY_DESCRIPTIONS)
		ELSE
			INSERT INTO ALLERGIES VALUES (1, @ALLERGY_NAME, @ALLERGY_DESCRIPTIONS)		
	END;