IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'ACTIVATE_USER')
BEGIN
	DROP PROC ACTIVATE_USER
END
GO
CREATE PROCEDURE ACTIVATE_USER
@ID_USER int,
@IS_RESULT int OUTPUT 
AS
BEGIN
IF(SELECT IS_ACTIVATED FROM Users WHERE IDUsers=@ID_USER)=1
BEGIN
SET @IS_RESULT=0;
RETURN 
END
ELSE
UPDATE USERS SET IS_ACTIVATED=1
WHERE IDUsers=@ID_USER
IF(SELECT IDUsers FROM Users WHERE IDUsers=@ID_USER)IS NULL
BEGIN
SET @IS_RESULT = -1;
END
ELSE 
BEGIN
SET @IS_RESULT = 1;
END
END;
