IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_MEDICAL_CARD_BY_USER_ID')
	DROP PROC GET_MEDICAL_CARD_BY_USER_ID

GO

CREATE PROCEDURE GET_MEDICAL_CARD_BY_USER_ID @ID_USER INT AS
BEGIN
	SELECT MEDICAL_CARD.ID AS "CARD.ID", MEDICAL_CARD.DESCRIPTION, MEDICAL_CARD.CURE, SCHEDULE.IDDOCTOR, SCHEDULE.IDPATIENT, SCHEDULE.START_DATETIME, SCHEDULE.ID AS "ID_VISIT", SUBDISEASES.SUBDISEASECODE
	FROM MEDICAL_CARD
	INNER JOIN SCHEDULE ON MEDICAL_CARD.ID_VISIT = SCHEDULE.ID
	LEFT JOIN SUBDISEASES ON MEDICAL_CARD.ID_DISEASE = SUBDISEASES.SUBDISEASEID
	WHERE SCHEDULE.IDPATIENT = @ID_USER;
END