-INSERT INTO RULES

INSERT INTO RULES(NAME,HOUR_START,HOUR_END,PERIOD_START,PERIOD_END,INCLUSIVE) VALUES('holidays','00:00:00','23:59:00','2018-05-01','2018-05-06',0);
INSERT INTO RULES(NAME,HOUR_START,HOUR_END,PERIOD_START,PERIOD_END,INCLUSIVE,MONDAY) VALUES('vikend','00:00:00','23:59:00','2018-12-12','2018-12-14',0,1);



--INSERT INTO RULESETS
INSERT INTO RULESETS(DOCTOR_ID,RULE_ID) VALUES (1,1);
INSERT INTO RULESETS(DOCTOR_ID,RULE_ID) VALUES (2,1);
INSERT INTO RULESETS(DOCTOR_ID,RULE_ID) VALUES (3,1);
INSERT INTO RULESETS(DOCTOR_ID,RULE_ID) VALUES (4,1);
INSERT INTO RULESETS(DOCTOR_ID,RULE_ID) VALUES (1,2);
INSERT INTO RULESETS(DOCTOR_ID,RULE_ID) VALUES (2,3);
INSERT INTO RULESETS(DOCTOR_ID,RULE_ID) VALUES (3,3);
INSERT INTO RULESETS(DOCTOR_ID,RULE_ID) VALUES (4,3);

          

