INSERT INTO MEDICAL_CARD (ID_VISIT, ID_DISEASE) VALUES (4,1);
INSERT INTO MEDICAL_CARD (ID_VISIT, ID_DISEASE) VALUES (5,2);
INSERT INTO MEDICAL_CARD (ID_VISIT, ID_DISEASE) VALUES (1,3);
INSERT INTO MEDICAL_CARD (ID_VISIT, ID_DISEASE) VALUES (2,4);
INSERT INTO MEDICAL_CARD (ID_VISIT, ID_DISEASE) VALUES (3,5);