INSERT INTO MEDICAL_CARD (ID_VISIT, ID_DISEASE) VALUES (11,1);
INSERT INTO MEDICAL_CARD (ID_VISIT, ID_DISEASE) VALUES (12,2);
INSERT INTO MEDICAL_CARD (ID_VISIT, ID_DISEASE) VALUES (13,3);
INSERT INTO MEDICAL_CARD (ID_VISIT, ID_DISEASE) VALUES (14,4);
INSERT INTO MEDICAL_CARD (ID_VISIT, ID_DISEASE) VALUES (15,5);