ALTER TABLE [dbo].[USERS_ALLERGIES] DROP CONSTRAINT [FK__USERS_ALL__USER___236943A5]
GO

ALTER TABLE [dbo].[USERS_ALLERGIES] DROP CONSTRAINT [FK__USERS_ALL__ALLER__245D67DE]
GO

DROP TABLE [dbo].[USERS_ALLERGIES]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USERS_ALLERGIES](
	[USER_ID] [int] NOT NULL,
	[ALLERGY_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[USER_ID],
    [ALLERGY_ID]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USERS_ALLERGIES]  WITH CHECK ADD FOREIGN KEY([ALLERGY_ID])
REFERENCES [dbo].[ALLERGIES] ([ID_ALLERGY])
GO

ALTER TABLE [dbo].[USERS_ALLERGIES]  WITH CHECK ADD FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USERS] ([IDUsers])
GO
