INSERT INTO USERS_ALLERGIES VALUES(1, 17, 1);
INSERT INTO USERS_ALLERGIES VALUES(2, 17, 2);
INSERT INTO USERS_ALLERGIES VALUES(3, 17, 4);
INSERT INTO USERS_ALLERGIES VALUES(4, 18, 3);
INSERT INTO USERS_ALLERGIES VALUES(5, 18, 2);
INSERT INTO USERS_ALLERGIES VALUES(6, 19, 4);
INSERT INTO USERS_ALLERGIES VALUES(7, 19, 2);
INSERT INTO USERS_ALLERGIES VALUES(8, 19, 1);
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_USER_ALLERGIES')
BEGIN
	DROP PROC GET_USER_ALLERGIES;
END;

GO
CREATE PROCEDURE GET_USER_ALLERGIES @USER_ID INT
AS
BEGIN
	SELECT ALLERGY_NAME 
	FROM ALLERGIES 
	WHERE ID_ALLERGY IN (SELECT ALLERGY_ID FROM USERS_ALLERGIES WHERE USER_ID=@USER_ID)
END