IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SALARY_RATES') 
BEGIN 
DROP TABLE SALARY_RATES
END;

BEGIN
CREATE TABLE SALARY_RATES(
ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
PROFFESION_ID INT NOT NULL FOREIGN KEY REFERENCES PROFESSIONS(IDProfessins),
RATE DECIMAL(19,2) NOT NULL CHECK(RATE>0),
PERIOD_START DATE NOT NULL,
CONSTRAINT UC_PERIOD_START_PROFFESION_ID UNIQUE (PROFFESION_ID, PERIOD_START)
 );
END;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SALARY_COEFFICIENT') 
BEGIN 
DROP TABLE SALARY_COEFFICIENT
END;

BEGIN
CREATE TABLE SALARY_COEFFICIENTs(
ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
DOCTOR_ID INT NOT NULL FOREIGN KEY REFERENCES DOCTORS(IDDoctors),
COEFFICIENT DECIMAL(3,2) NOT NULL,
PERIOD_START DATE NOT NULL,
CONSTRAINT UC_PERIOD_START_DOCTOR_ID UNIQUE (DOCTOR_ID,PERIOD_START)
);
END;
