INSERT INTO USERS_ALLERGIES VALUES(1, 17, 1);
INSERT INTO USERS_ALLERGIES VALUES(2, 17, 2);
INSERT INTO USERS_ALLERGIES VALUES(3, 17, 4);
INSERT INTO USERS_ALLERGIES VALUES(4, 18, 3);
INSERT INTO USERS_ALLERGIES VALUES(5, 18, 2);
INSERT INTO USERS_ALLERGIES VALUES(6, 19, 4);
INSERT INTO USERS_ALLERGIES VALUES(7, 19, 2);
INSERT INTO USERS_ALLERGIES VALUES(8, 19, 1);
