IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_USER_ALLERGIES')
BEGIN
	DROP PROC GET_USER_ALLERGIES;
END;

GO
CREATE PROCEDURE GET_USER_ALLERGIES @USER_ID INT
AS
BEGIN
	SELECT ALLERGY_NAME 
	FROM ALLERGIES 
	WHERE ID_ALLERGY IN (SELECT ALLERGY_ID FROM USERS_ALLERGIES WHERE USER_ID=@USER_ID)
END
