IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SELECT_RULES')
BEGIN
	DROP PROC SELECT_RULES
END
GO
CREATE PROCEDURE SELECT_RULES
@FROM DATE,@TILL DATE, @IDDOCTOR int
AS
BEGIN
SELECT NAME,HOUR_START,HOUR_END,PERIOD_START,PERIOD_END,INCLUSIVE,SUNDAY,MONDAY,TUESDAY,WEDNESDAY,THIRSDAY,FRIDAY,SATURDAY,DOCTOR_ID,RULE_ID FROM RULES INNER JOIN RULESETS ON RULE_ID=RULES.ID 
WHERE PERIOD_START>=@FROM AND PERIOD_END<=@TILL AND DOCTOR_ID=@IDDOCTOR;
END;   
  
      
