IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SALARY_RATES') 
 BEGIN 
 DROP TABLE SALARY_RATES
 END;

 BEGIN
CREATE TABLE SALARY_RATES(RATEID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
IDProfessins INT NOT NULL FOREIGN KEY REFERENCES PROFESSIONS(IDProfessins),
RATE DECIMAL(19,2) NOT NULL CHECK(RATE>0),PERIOD_START DATE NOT NULL,
CONSTRAINT UC_PERIOD_START_IDProfessins UNIQUE (IDProfessins,PERIOD_START)
 
 );
END;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SALARY_COEFFICIENT') 
 BEGIN 
 DROP TABLE SALARY_COEFFICIENT
 END;

 BEGIN
CREATE TABLE SALARY_COEFFICIENT(COEFFICIENTID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
IDDoctors INT NOT NULL FOREIGN KEY REFERENCES DOCTORS(IDDoctors),
COEFFICIENT DECIMAL(3,2) NOT NULL,PERIOD_START DATE NOT NULL,
CONSTRAINT UC_PERIOD_START_IDDoctors UNIQUE (IDDoctors,PERIOD_START)
);
END;
