IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_SALARY_STATISTICS_FOR_PERIOD')
	DROP PROC GET_SALARY_STATISTICS_FOR_PERIOD
GO
CREATE PROCEDURE GET_SALARY_STATISTICS_FOR_PERIOD
	@DOCTOR_ID INT,
	@START_DATE DATETIME,
	@END_DATE DATETIME
AS
BEGIN
	DECLARE @SPECIFIS_DAY  DATETIME
	SET @SPECIFIS_DAY = @START_DATE
	DECLARE @TEMP table(DAYY DATETIME, WORKED_HOURS DECIMAL (4,2), RATE DECIMAL (8, 2), COEFFICIENT DECIMAL (4,2), TOTAL DECIMAL(8,2))
	WHILE @SPECIFIS_DAY <= @END_DATE
	BEGIN
		INSERT INTO @TEMP EXEC GET_SALARY_STATISTICS_FOR_DAY @DOCTOR_ID, @SPECIFIS_DAY
		SET @SPECIFIS_DAY = DATEADD(DAY, 1, @SPECIFIS_DAY)
	END;
	SELECT * FROM @TEMP
END;
