DROP TABLE IF EXISTS dbo.USERS_ALLERGIES;

CREATE TABLE USERS_ALLERGIES (
    USER_ID INT NOT NULL,
    ALLERGY_ID INT NOT NULL,
    CONSTRAINT PK_USERS_ALLERGIES PRIMARY KEY (USER_ID, ALLERGY_ID)
);
