IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'EDIT_USER_INFO')
DROP PROC EDIT_USER_INFO;
GO
CREATE PROCEDURE EDIT_USER_INFO
@ID int, @PHONE NVARCHAR(13), @SEX BIT, @COUNTRY NVARCHAR(60), @CITY NVARCHAR(60), @STREET NVARCHAR(60), @APARTMENT NVARCHAR(10),
@FIRSTNAME NVARCHAR(30), @LASTNAME NVARCHAR(30), @EMAIL NVARCHAR(40)
AS
BEGIN
IF ((SELECT COUNT(*) FROM USERS WHERE IDUsers = @ID) = 0)
BEGIN
RETURN 0;
END;
UPDATE USERS SET
FIRSTNAME=@FIRSTNAME, LASTNAME=@LASTNAME, EMAIL=@EMAIL
WHERE IDUsers=@ID;
UPDATE USER_INFO SET
PHONE=@PHONE, SEX=@SEX, COUNTRY=@COUNTRY, CITY=@CITY, STREET=@STREET, APARTMENT=@APARTMENT
WHERE ID = @ID;
RETURN 1;
END;
GO

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_ALL_USER_INFO')
DROP PROC GET_ALL_USER_INFO;
GO
CREATE PROCEDURE GET_ALL_USER_INFO
@ID int
AS
BEGIN
SELECT ID, FIRSTNAME, LASTNAME, PASSWORD, EMAIL, PHONE, SEX, COUNTRY, CITY, STREET, APARTMENT FROM USERS INNER JOIN USER_INFO ON IDUsers = ID WHERE ID = @ID;
END;