IF (OBJECT_ID('dbo.UC_SCHEDULE_DOCTOR', 'UQ') IS NOT NULL)
    ALTER TABLE dbo.SCHEDULE DROP CONSTRAINT UC_SCHEDULE_DOCTOR

ALTER TABLE SCHEDULE ADD CONSTRAINT UC_SCHEDULE_DOCTOR UNIQUE (IDDOCTOR, START_DATETIME)


IF (OBJECT_ID('dbo.UC_SCHEDULE_PATIENT', 'UQ') IS NOT NULL)
    ALTER TABLE dbo.SCHEDULE DROP CONSTRAINT UC_SCHEDULE_PATIENT

ALTER TABLE SCHEDULE ADD CONSTRAINT UC_SCHEDULE_PATIENT UNIQUE (IDPATIENT, START_DATETIME)
