IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'DISMISS_DOCTOR_FROM_RULE')
DROP PROC DISMISS_DOCTOR_FROM_RULE;
GO
CREATE PROCEDURE DISMISS_DOCTOR_FROM_RULE
@RULE_ID INT, @DOCTOR_ID INT
AS
BEGIN
DELETE FROM RULESETS WHERE RULE_ID=@RULE_ID AND DOCTOR_ID=@DOCTOR_ID;
END;
GO