IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'USER_INFO') 
	DROP TABLE USERINFO;
CREATE TABLE USER_INFO(
ID INT PRIMARY KEY FOREIGN KEY REFERENCES USERS(IDUsers) ON DELETE CASCADE,
PHONE NVARCHAR(13),
--1 - male, 0 - female
SEX BIT,
COUNTRY NVARCHAR(60),
CITY NVARCHAR(60),
STREET NVARCHAR(60),
APARTMENT NVARCHAR(10)
);