IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_DOCTORS_WITH_RULE')
DROP PROC GET_DOCTORS_WITH_RULE;

GO
CREATE PROCEDURE GET_DOCTORS_WITH_RULE
@ID int
AS
BEGIN
SELECT RULE_ID,DOCTOR_ID,FIRSTNAME,LASTNAME,PROFESSINNAME FROM RULESETS
INNER JOIN DOCTORS ON RULESETS.DOCTOR_ID = DOCTORS.IDDoctors
INNER JOIN USERS ON DOCTORS.IDDoctors = USERS.IDUsers
INNER JOIN PROFESSIONS ON DOCTORS.IDPROFESSION = PROFESSIONS.IDProfessins
WHERE RULE_ID = @ID ;
END;
