IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_RATE_FOR_PROFESSION')
	DROP PROC GET_RATE_FOR_PROFESSION;

GO
CREATE PROCEDURE GET_RATE_FOR_PROFESSION
@ID INT
AS
BEGIN
	SELECT TOP 1 RATE, PERIOD_START FROM SALARY_RATES WHERE PROFFESION_ID = @ID AND PERIOD_START <= GETDATE()
	UNION
	SELECT RATE, PERIOD_START FROM SALARY_RATES WHERE PROFFESION_ID = @ID AND PERIOD_START > GETDATE()
END;
