BEGIN TRANSACTION;

INSERT INTO PATIENT_DISEASES 
SELECT TOP 10 SUBDISEASEID,
(SELECT TOP 1 ID FROM SCHEDULE),
GETDATE()
FROM SUBDISEASES;

INSERT INTO PATIENT_DISEASES(ID_DISEASE,ID_VISIT)
SELECT TOP 10 SUBDISEASEID,
(SELECT MAX(ID) FROM SCHEDULE)
FROM SUBDISEASES;

 INSERT INTO PATIENT_ALLERGIES
 SELECT TOP 10 ID_ALLERGY ,
 (SELECT TOP 1 ID
 FROM SCHEDULE)
 FROM ALLERGIES;

 INSERT INTO PATIENT_ALLERGIES(ID_VISIT,ID_ALLERGY)
 SELECT TOP 10 ID,
 (SELECT TOP 1 ID_ALLERGY FROM ALLERGIES)
 FROM SCHEDULE;
 
 COMMIT TRANSACTION;
