IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PATIENT_DISEASES') 
	BEGIN 
		DROP TABLE PATIENT_DISEASES
	END

	BEGIN
		CREATE TABLE PATIENT_DISEASES (
			ID INT IDENTITY(1,1) PRIMARY KEY,
			ID_DISEASE INT NOT NULL FOREIGN KEY REFERENCES SUBDISEASES(SUBDISEASEID),
			ID_VISIT INT NOT NULL FOREIGN KEY REFERENCES SCHEDULE(ID),
			END_DATETIME DATETIME
			)
		END;

   IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PATIENT_ALLERGIES') 
	BEGIN 
		DROP TABLE PATIENT_ALLERGIES
	END

	BEGIN
		CREATE TABLE PATIENT_ALLERGIES (
			ID INT IDENTITY(1,1) PRIMARY KEY,
			ID_ALLERGY INT NOT NULL FOREIGN KEY REFERENCES ALLERGIES(ID_ALLERGY),
			ID_VISIT INT NOT NULL FOREIGN KEY REFERENCES SCHEDULE(ID)
			)
		END;

