IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_COEFF_FOR_DOCTOR_FUTURE')
	DROP PROC GET_COEFF_FOR_DOCTOR_FUTURE;

GO
CREATE PROCEDURE GET_COEFF_FOR_DOCTOR_FUTURE
@DOCTOR_ID INT
AS
BEGIN
	SELECT * FROM 
	(SELECT TOP 1 COEFFICIENT, PERIOD_START FROM SALARY_COEFFICIENTS WHERE DOCTOR_ID = @DOCTOR_ID AND PERIOD_START <= GETDATE() ORDER BY PERIOD_START DESC) as T
	UNION
	SELECT COEFFICIENT, PERIOD_START FROM SALARY_COEFFICIENTS WHERE DOCTOR_ID = @DOCTOR_ID AND PERIOD_START > GETDATE() ORDER BY PERIOD_START ASC
END;

GO
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_COEFF_FOR_DOCTOR_PAST')
	DROP PROC GET_COEFF_FOR_DOCTOR_PAST;

GO
CREATE PROCEDURE GET_COEFF_FOR_DOCTOR_PAST
@DOCTOR_ID INT
AS
BEGIN
	DECLARE @ACTIVE_DATE DATETIME;
	SET @ACTIVE_DATE = (SELECT TOP 1 PERIOD_START FROM SALARY_COEFFICIENTS WHERE DOCTOR_ID = @DOCTOR_ID AND PERIOD_START <= GETDATE() ORDER BY PERIOD_START DESC);
	PRINT @ACTIVE_DATE;
	SELECT COEFFICIENT, PERIOD_START FROM SALARY_COEFFICIENTS WHERE DOCTOR_ID = @DOCTOR_ID AND PERIOD_START < @ACTIVE_DATE ORDER BY PERIOD_START ASC;
END;