IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'ADD_NEW_COEFF')
	DROP PROC ADD_NEW_COEFF;

GO
CREATE PROCEDURE ADD_NEW_COEFF
	@DOCTOR_ID INT,
	@COEFFICIENT DECIMAL (19,2),
	@START_DATE DATETIME
AS
BEGIN TRY
	IF (@START_DATE > GETDATE())
		BEGIN
		INSERT INTO SALARY_COEFFICIENTS VALUES (@DOCTOR_ID, @COEFFICIENT, @START_DATE);	
		RETURN 1;
		END;
	ELSE
		RETURN 0;
END TRY
BEGIN CATCH
	RETURN 0;
END CATCH