IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'DELETE_SOME_RATE')
	DROP PROC DELETE_SOME_RATE;

GO
CREATE PROCEDURE DELETE_SOME_RATE
	@PROFFESION_ID INT,
	@START_DATE DATETIME
AS
BEGIN
	IF ((SELECT COUNT(*) FROM SALARY_RATES WHERE PROFFESION_ID = @PROFFESION_ID AND PERIOD_START = @START_DATE) = 1)
		BEGIN	
		DECLARE @ACTIVE_DATE DATETIME;
		SET @ACTIVE_DATE = (SELECT TOP 1 PERIOD_START FROM SALARY_RATES WHERE PROFFESION_ID = @PROFFESION_ID AND PERIOD_START <= GETDATE() ORDER BY PERIOD_START DESC);
		PRINT @ACTIVE_DATE;
		IF (@START_DATE > @ACTIVE_DATE ) 
			BEGIN
			DELETE FROM SALARY_RATES WHERE PROFFESION_ID = @PROFFESION_ID AND PERIOD_START = @START_DATE;
			RETURN 1;
			END;
		ELSE 
			BEGIN
			RETURN 0;
			END;
		END;
	ELSE
		RETURN 0;
END;