IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_RATE_FOR_PROFESSION')
	DROP PROC GET_RATE_FOR_PROFESSION;

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_RATE_FOR_PROFESSION_FUTURE')
	DROP PROC GET_RATE_FOR_PROFESSION_FUTURE;

GO
CREATE PROCEDURE GET_RATE_FOR_PROFESSION_FUTURE
@PROFFESION_ID INT
AS
BEGIN
	SELECT * FROM 
	(SELECT TOP 1 RATE, PERIOD_START FROM SALARY_RATES WHERE PROFFESION_ID = @PROFFESION_ID AND PERIOD_START <= GETDATE() ORDER BY PERIOD_START DESC) as T
	UNION
	SELECT RATE, PERIOD_START FROM SALARY_RATES WHERE PROFFESION_ID = @PROFFESION_ID AND PERIOD_START > GETDATE() ORDER BY PERIOD_START ASC
END;

GO
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_RATE_FOR_PROFESSION_PAST')
	DROP PROC GET_RATE_FOR_PROFESSION_PAST;

GO
CREATE PROCEDURE GET_RATE_FOR_PROFESSION_PAST
@PROFFESION_ID INT
AS
BEGIN
	DECLARE @ACTIVE_DATE DATETIME;
	SET @ACTIVE_DATE = (SELECT TOP 1 PERIOD_START FROM SALARY_RATES WHERE PROFFESION_ID = @PROFFESION_ID AND PERIOD_START <= GETDATE() ORDER BY PERIOD_START DESC);
	PRINT @ACTIVE_DATE;
	SELECT RATE, PERIOD_START FROM SALARY_RATES WHERE PROFFESION_ID = @PROFFESION_ID AND PERIOD_START < @ACTIVE_DATE ORDER BY PERIOD_START ASC;
END;