IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'ADD_NEW_RATE')
	DROP PROC ADD_NEW_RATE;

GO
CREATE PROCEDURE ADD_NEW_RATE
	@PROFFESION_ID INT,
	@RATE DECIMAL (19,2),
	@START_DATE DATETIME
AS
BEGIN TRY
	IF (@START_DATE > GETDATE())
		BEGIN
		INSERT INTO SALARY_RATES VALUES (@PROFFESION_ID, @RATE, @START_DATE);	
		RETURN 1;
		END;
	ELSE
		RETURN 0;
END TRY
BEGIN CATCH
	RETURN 0;
END CATCH