IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name ='ACTIVE_ALLERGY')
BEGIN
	DROP PROC ACTIVE_ALLERGY
END
GO
CREATE PROCEDURE ACTIVE_ALLERGY
@ID_USER int
AS
BEGIN
      SELECT ALLERGY_ID,ALLERGY_NAME,ID_VISIT,START_DATETIME,IDPATIENT FROM(SELECT * FROM ALLERGIES
      LEFT JOIN USERS_ALLERGIES
      ON ALLERGIES.ID_ALLERGY=USERS_ALLERGIES.ALLERGY_ID)AS ALL_ALLERGY 
      INNER JOIN SCHEDULE 
      ON ALL_ALLERGY.ID_VISIT=SCHEDULE.ID
      WHERE SCHEDULE.IDPATIENT=@ID_USER AND (ALL_ALLERGY.END_DATETIME IS NULL)
END;
--------------------------------------------------------------------------------
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name ='NON_ACTIVE_ALLERGY')
BEGIN
	DROP PROC NON_ACTIVE_ALLERGY
END
GO
CREATE PROCEDURE NON_ACTIVE_ALLERGY
@ID_USER int
AS
      BEGIN
      SELECT DISTINCT ID_ALLERGY, ALLERGY_NAME
      FROM   ALLERGIES 
      LEFT JOIN USERS_ALLERGIES
      ON ALLERGIES.ID_ALLERGY=USERS_ALLERGIES.ALLERGY_ID
      WHERE ALLERGY_ID NOT IN(SELECT ALLERGY_ID FROM USERS_ALLERGIES INNER JOIN SCHEDULE ON SCHEDULE.ID=ID_VISIT WHERE IDPATIENT=@ID_USER)
      OR (ALLERGY_ID IS NULL OR USERS_ALLERGIES.END_DATETIME<=GETDATE());
END;
