IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PATIENT_DISEASES') 
	BEGIN 
		DROP TABLE PATIENT_DISEASES
	END

	BEGIN
		CREATE TABLE PATIENT_DISEASES (
			ID INT IDENTITY(1,1) PRIMARY KEY,
			ID_DISEASE INT NOT NULL FOREIGN KEY REFERENCES SUBDISEASES(SUBDISEASEID),
			ID_VISIT INT NOT NULL FOREIGN KEY REFERENCES SCHEDULE(ID),
			END_DATETIME INT FOREIGN KEY REFERENCES SCHEDULE(ID) 
			)
		END;

  IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'USERS_ALLERGIES') 
	BEGIN 
		DROP TABLE USERS_ALLERGIES
	END
	BEGIN
			CREATE TABLE USERS_ALLERGIES(
			ID INT IDENTITY(1,1) PRIMARY KEY,
			ALLERGY_ID INT NOT NULL FOREIGN KEY REFERENCES ALLERGIES(ID_ALLERGY),
			ID_VISIT INT NOT NULL FOREIGN KEY REFERENCES SCHEDULE(ID),
			END_DATETIME INT FOREIGN KEY REFERENCES SCHEDULE(ID)
			);
		END;
