IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_ALL_USER_INFO')
DROP PROC GET_ALL_USER_INFO;
GO
CREATE PROCEDURE GET_ALL_USER_INFO
@ID int
AS
BEGIN
SELECT ID, FIRSTNAME, LASTNAME, PASSWORD, EMAIL, PHONE, SEX, COUNTRY, CITY, STREET, APARTMENT FROM USERS LEFT JOIN USER_INFO ON IDUsers = ID WHERE ID = @ID;
END;