IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'CHECK_IF_DESCRIPTION_EXISTS')
	DROP PROC CHECK_IF_DESCRIPTION_EXISTS;

GO
CREATE PROCEDURE CHECK_IF_DESCRIPTION_EXISTS
	@IDPATIENT INT,
	@START_DATETIME DATETIME
AS
BEGIN
	DECLARE @EXISTS INT;
	SET @EXISTS = (	SELECT COUNT(ID_VISIT) FROM MEDICAL_CARD 
	WHERE ID_VISIT = (SELECT ID FROM SCHEDULE WHERE IDPATIENT=@IDPATIENT AND START_DATETIME=@START_DATETIME) )
	RETURN @EXISTS
END;