IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name ='NON_ACTIVE_ALLERGY')
BEGIN
	DROP PROC NON_ACTIVE_ALLERGY
END
GO
CREATE PROCEDURE NON_ACTIVE_ALLERGY
@ID_USER INT
AS
BEGIN
    SELECT DISTINCT ID_ALLERGY, ALLERGY_NAME
      FROM   ALLERGIES 
      LEFT JOIN USERS_ALLERGIES
      ON ALLERGIES.ID_ALLERGY=USERS_ALLERGIES.ALLERGY_ID
      WHERE ALLERGY_ID NOT IN(
	  SELECT ALLERGY_ID FROM(SELECT * FROM ALLERGIES
      LEFT JOIN USERS_ALLERGIES
      ON ALLERGIES.ID_ALLERGY=USERS_ALLERGIES.ALLERGY_ID)AS ALL_ALLERGY 
      INNER JOIN SCHEDULE 
      ON ALL_ALLERGY.ID_VISIT=SCHEDULE.ID
      WHERE SCHEDULE.IDPATIENT=@ID_USER AND (ALL_ALLERGY.END_DATETIME IS NULL)
	  );
END;
