BEGIN TRANSACTION
	INSERT INTO PATIENT_DISEASES (ID_VISIT, ID_DISEASE)
	SELECT TOP 10 ID, (SELECT TOP 1 SUBDISEASEID FROM SUBDISEASES ORDER BY NEWID())
	FROM SCHEDULE WHERE IDPATIENT < 100 ORDER BY NEWID()

	INSERT INTO PATIENT_DISEASES (ID_VISIT, ID_DISEASE)
	SELECT TOP 10 ID, (SELECT TOP 1 SUBDISEASEID FROM SUBDISEASES ORDER BY NEWID())
	FROM SCHEDULE WHERE IDPATIENT > 100 ORDER BY NEWID()
COMMIT TRANSACTION
