BEGIN TRANSACTION;
EXEC INSERT_NEW_ALLERGY_NAME_AND_ALLERGY_DESCRIPTION 'Mushrooms', 'Mushrooms allergy description'
EXEC INSERT_NEW_ALLERGY_NAME_AND_ALLERGY_DESCRIPTION 'Oranges', 'Oranges allergy description'
EXEC INSERT_NEW_ALLERGY_NAME_AND_ALLERGY_DESCRIPTION 'Dust', 'Dust allergy description'
EXEC INSERT_NEW_ALLERGY_NAME_AND_ALLERGY_DESCRIPTION 'Penicillin', 'Penicillin allergy description'
EXEC INSERT_NEW_ALLERGY_NAME_AND_ALLERGY_DESCRIPTION 'Wool', 'Wool allergy description'
EXEC INSERT_NEW_ALLERGY_NAME_AND_ALLERGY_DESCRIPTION 'Mildew', 'Mildew allergy description'
EXEC INSERT_NEW_ALLERGY_NAME_AND_ALLERGY_DESCRIPTION 'Pollen', 'Pollen allergy description'
COMMIT TRANSACTION;