IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name ='NON_ACTIVE_DISEASES_FOR_CATEGORY')
BEGIN
	DROP PROC NON_ACTIVE_DISEASES_FOR_CATEGORY
END
GO
CREATE PROCEDURE NON_ACTIVE_DISEASES_FOR_CATEGORY
@ID_USER INT,@DISEASEID INT
AS
BEGIN
    SELECT DISTINCT SUBDISEASES.SUBDISEASEID, SUBDISEASES.SUBDISEASENAME,FIRSTCODE,LASTCODE
	  FROM ICATEGORIES INNER JOIN SUBCATEGORIES ON CATEGORYCODE=CATEGORYID INNER JOIN DISEASES ON SUBCATEGORIEID=SUBCATEGORYID
	  INNER JOIN SUBDISEASES ON DISEASES.DISEASEID=SUBDISEASES.DISEASEID 
	  LEFT JOIN PATIENT_DISEASES
    ON SUBDISEASES.SUBDISEASEID=PATIENT_DISEASES.ID_DISEASE
    WHERE (ID_DISEASE NOT IN(SELECT ID_DISEASE FROM PATIENT_DISEASES INNER JOIN SCHEDULE ON SCHEDULE.ID=ID_VISIT WHERE IDPATIENT=@ID_USER AND PATIENT_DISEASES.END_DATETIME IS NULL)
    OR (ID_DISEASE IS NULL)) AND SUBDISEASES.DISEASEID=@DISEASEID;
END;

