IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_PAGE_COUNT_FOR_MC_DEPENDING_ELEM_COUNT')
	DROP PROC GET_PAGE_COUNT_FOR_MC_DEPENDING_ELEM_COUNT

GO
CREATE PROCEDURE GET_PAGE_COUNT_FOR_MC_DEPENDING_ELEM_COUNT @USER_ID INT, @ELEMENT_COUNT INT
AS
BEGIN
	WITH NUMBERED_MY_TABLE AS
	(
  	SELECT  ROW_NUMBER() OVER (ORDER BY SCHEDULE.START_DATETIME DESC) AS ROWNUMBER
		FROM PATIENT_DISEASES
		INNER JOIN SCHEDULE ON PATIENT_DISEASES.ID_VISIT= SCHEDULE.ID
		LEFT JOIN SUBDISEASES ON PATIENT_DISEASES.ID_DISEASE = SUBDISEASES.SUBDISEASEID
		INNER JOIN USERS ON IDDOCTOR= USERS.IDUsers
		WHERE (SCHEDULE.IDPATIENT = @USER_ID)
	)

	SELECT CEILING(COUNT(ROWNUMBER) / @ELEMENT_COUNT) + 1
	FROM NUMBERED_MY_TABLE
END
