IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SELECT_RULES')
BEGIN
	DROP PROC SELECT_RULES
END
GO
CREATE PROCEDURE SELECT_RULES
@FROM DATE,@TILL DATE, @IDDOCTOR int
AS
BEGIN
SELECT NAME,HOUR_START,HOUR_END,PERIOD_START,PERIOD_END,INCLUSIVE,SUNDAY,MONDAY,TUESDAY,WEDNESDAY,THIRSDAY,FRIDAY,SATURDAY,DOCTOR_ID,RULE_ID 
FROM RULES INNER JOIN RULESETS ON RULE_ID=RULES.ID 

WHERE ((PERIOD_START BETWEEN @FROM AND @TILL) OR (PERIOD_END BETWEEN @FROM AND @TILL) OR (@FROM BETWEEN PERIOD_START AND PERIOD_END)) AND DOCTOR_ID=@IDDOCTOR
ORDER BY INCLUSIVE DESC;
END;
