IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_PAGE_COUNT_FOR_MC_DEPENDING_ELEM_COUNT')
	DROP PROC GET_PAGE_COUNT_FOR_MC_DEPENDING_ELEM_COUNT


GO
CREATE PROCEDURE GET_PAGE_COUNT_FOR_MC_DEPENDING_ELEM_COUNT @USER_ID INT, @ELEMENT_COUNT INT
AS
BEGIN
	WITH NUMBERED_MY_TABLE AS
	(
		SELECT  MEDICAL_CARD.ID AS "CARD_ID", MEDICAL_CARD.DESCRIPTION, MEDICAL_CARD.CURE, USERS.FIRSTNAME AS DOCTOR_FIRSTNAME, USERS.LASTNAME AS DOCTOR_LASTNAME,
		SCHEDULE.IDPATIENT, SCHEDULE.START_DATETIME AS SESSION_START_DATETIME,
		SCHEDULE.ID AS "ID_VISIT", ROW_NUMBER() OVER (ORDER BY SCHEDULE.START_DATETIME DESC) AS ROWNUMBER
		FROM MEDICAL_CARD
		INNER JOIN SCHEDULE ON MEDICAL_CARD.ID_VISIT = SCHEDULE.ID
		INNER JOIN USERS ON IDDOCTOR= USERS.IDUsers
		WHERE (SCHEDULE.IDPATIENT = @USER_ID)
	)

	SELECT CEILING(CONVERT(DECIMAL(10,2),COUNT(ROWNUMBER)) / @ELEMENT_COUNT)
	FROM NUMBERED_MY_TABLE
END