IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name ='GET_MEDICAL_RECORDS_FOR_USER')
BEGIN
	DROP PROC GET_MEDICAL_RECORDS_FOR_USER
END
GO

CREATE PROCEDURE GET_MEDICAL_RECORDS_FOR_USER
@ID_USER INT, @ELEMENT_COUNT INT, @PAGE_NUMBER INT AS
BEGIN
	WITH NUMBERED_MY_TABLE AS
	(
		SELECT  MEDICAL_CARD.ID AS "CARD_ID", MEDICAL_CARD.DESCRIPTION, MEDICAL_CARD.CURE, USERS.FIRSTNAME AS DOCTOR_FIRSTNAME, USERS.LASTNAME AS DOCTOR_LASTNAME,
		SCHEDULE.IDPATIENT, SCHEDULE.START_DATETIME AS SESSION_START_DATETIME,
		SCHEDULE.ID AS "ID_VISIT", ROW_NUMBER() OVER (ORDER BY SCHEDULE.START_DATETIME DESC) AS ROWNUMBER
		FROM MEDICAL_CARD
		INNER JOIN SCHEDULE ON MEDICAL_CARD.ID_VISIT = SCHEDULE.ID
		INNER JOIN USERS ON IDDOCTOR= USERS.IDUsers
		WHERE (SCHEDULE.IDPATIENT = 73)
	)
	SELECT CARD_ID, DESCRIPTION, CURE, DOCTOR_FIRSTNAME, DOCTOR_LASTNAME, IDPATIENT, SESSION_START_DATETIME, ID_VISIT
	FROM NUMBERED_MY_TABLE
	WHERE ROWNUMBER BETWEEN (1-1) * 4 + 1 AND 4 * 1
	ORDER BY SESSION_START_DATETIME DESC;
END;
