IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'ACTIVATE_USER')
BEGIN
	DROP PROC ACTIVATE_USER
END
GO
CREATE PROCEDURE ACTIVATE_USER
@ID_USER int
AS
BEGIN
UPDATE USERS SET IS_ACTIVATED=1

WHERE IDUsers=@ID_USER
END;
