IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SALARY_COEFFICIENTS') 
BEGIN 
DROP TABLE SALARY_COEFFICIENTS
END;

BEGIN
CREATE TABLE SALARY_COEFFICIENTS(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	DOCTOR_ID INT NOT NULL FOREIGN KEY REFERENCES DOCTORS(IDDoctors),
	COEFFICIENT DECIMAL(19,2) NOT NULL,
	PERIOD_START DATE NOT NULL,
	CONSTRAINT UC_PERIOD_START_DOCTOR_ID UNIQUE (DOCTOR_ID,PERIOD_START)
);
END;