----INSERT INTO
INSERT INTO SALARY_COEFFICIENTS 
SELECT IDDoctors,1,'2015-11-01'
FROM DOCTORS

----INSERT INTO
INSERT INTO SALARY_COEFFICIENTS 
SELECT IDDoctors,2,'2018-04-01'
FROM DOCTORS

----INSERT INTO
INSERT INTO SALARY_COEFFICIENTS 
SELECT IDDoctors,2.3,'2019-11-01'
FROM DOCTORS