IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name ='GET_PAGINATION_COUNT_FILTERED')
BEGIN
 DROP PROC GET_PAGINATION_COUNT_FILTERED
END
GO
CREATE PROCEDURE GET_PAGINATION_COUNT_FILTERED
@COUNTINPAGE INT,@PAGINATION INT OUTPUT, @ISADMIN BIT,@ISADOCTOR BIT,@FIRSTORLASTNAME NVARCHAR(30)=NULL
AS
BEGIN
DECLARE @TABLE TABLE(IDUsers INT, FIRSTNAME NVARCHAR(500),LASTNAME NVARCHAR(500), CHECKISADMIN BIT, PROFESSINNAME NVARCHAR(500));
INSERT INTO @TABLE EXEC FILTERING_USERS 1,30000,@ISADMIN,@ISADOCTOR,@FIRSTORLASTNAME;
SET @PAGINATION=CEILING(CAST((SELECT COUNT(*) FROM @TABLE)/CAST(@COUNTINPAGE AS FLOAT)AS FLOAT));
END;