IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_USER_AVAILABLE_ROLE')
	DROP PROC GET_USER_AVAILABLE_ROLE;

GO
CREATE PROCEDURE GET_USER_AVAILABLE_ROLE
	@IDUsers INT
AS
BEGIN
	DECLARE @SELECTED NVARCHAR(20)
	SET @SELECTED =( SELECT ROLENAME FROM ROLES 
	JOIN USERS ON USERS.IDROLE = ROLES.IDRoles
	WHERE IDUsers = @IDUsers);
	SELECT IDRoles, ROLENAME FROM ROLES 
	WHERE ROLENAME <> @SELECTED 
END;