IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_USER_ALLERGY_INFO')
DROP PROC GET_USER_ALLERGY_INFO;

GO
CREATE PROCEDURE GET_USER_ALLERGY_INFO
  @PATIENT_ID INT,
  @ALLERGY_ID INT
AS
BEGIN
  SELECT USERS.FIRSTNAME, USERS.LASTNAME, SCHEDULE.START_DATETIME, MEDICAL_CARD.DESCRIPTION, MEDICAL_CARD.CURE
	FROM (USERS_ALLERGIES INNER JOIN SCHEDULE ON USERS_ALLERGIES.ID_VISIT = SCHEDULE.ID
							LEFT JOIN MEDICAL_CARD ON USERS_ALLERGIES.ID_VISIT = MEDICAL_CARD.ID_VISIT
							INNER JOIN USERS ON SCHEDULE.IDDOCTOR=USERS.IDUsers) 
	WHERE (USERS_ALLERGIES.ALLERGY_ID = @ALLERGY_ID AND IDPATIENT = @PATIENT_ID AND USERS_ALLERGIES.END_DATETIME IS NULL);
END;
