IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_USER_ROLE')
	DROP PROC GET_USER_ROLE;

GO
CREATE PROCEDURE GET_USER_ROLE
	@IDUsers INT
AS
BEGIN
	SELECT FIRSTNAME, LASTNAME, ROLENAME FROM USERS 
	INNER JOIN ROLES ON USERS.IDROLE = ROLES.IDRoles 
	WHERE IDUsers = @IDUsers;
END;