IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name ='CLOSE_DISEASE')
BEGIN
	DROP PROC CLOSE_DISEASE
END
GO
CREATE PROCEDURE CLOSE_DISEASE
@ID_USER INT,@ID_DISEASE INT,@START_VISIT_TIME DATETIME
    AS
    BEGIN
      IF EXISTS(SELECT * FROM PATIENT_DISEASES INNER JOIN SCHEDULE
      ON SCHEDULE.ID=PATIENT_DISEASES.ID_VISIT
      WHERE IDPATIENT=@ID_USER AND ID_DISEASE=@ID_DISEASE AND START_DATETIME=@START_VISIT_TIME AND PATIENT_DISEASES.END_DATETIME IS NOT NULL)
      RETURN 0;
      ELSE 
	BEGIN
			BEGIN TRANSACTION;
			UPDATE PATIENT_DISEASES
			SET END_DATETIME=(SELECT SCHEDULE.ID FROM SCHEDULE WHERE START_DATETIME=@START_VISIT_TIME AND IDPATIENT=@ID_USER AND PATIENT_DISEASES.END_DATETIME IS NULL)
			WHERE ID_DISEASE=@ID_DISEASE AND ID_VISIT=(SELECT SCHEDULE.ID FROM SCHEDULE JOIN PATIENT_DISEASES ON SCHEDULE.ID=PATIENT_DISEASES.ID_VISIT
			WHERE IDPATIENT=@ID_USER AND ID_DISEASE=@ID_DISEASE AND PATIENT_DISEASES.END_DATETIME IS NULL );
			COMMIT TRANSACTION;
			RETURN 1;
	END;
	END
       
