IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name ='LIST_USER_FOR_ROLE')
BEGIN
 DROP PROC LIST_USER_FOR_ROLE
END
GO
CREATE PROCEDURE LIST_USER_FOR_ROLE 
 @TEXT NVARCHAR(30)
AS
BEGIN
SELECT FIRSTNAME,LASTNAME FROM USERS WHERE FIRSTNAME LIKE'%'+@TEXT+'%' OR LASTNAME LIKE'%'+@TEXT+'%'
END;
