IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name ='FILTERING_USERS')
BEGIN
 DROP PROC FILTERING_USERS
END
GO
CREATE PROCEDURE FILTERING_USERS
@PAGENUMBER INT,@COUNTINPAGE INT,@ISADMIN BIT,@ISADOCTOR BIT,@FIRSTORLASTNAME NVARCHAR(30)=NULL
AS
IF(@FIRSTORLASTNAME IS NULL)
BEGIN
WITH ISADMIN(IDUsers,IDROLE,CHECKISADMIN)
AS
(SELECT IDUsers,IDROLE, CASE WHEN IDROLE = 1 THEN 1 ELSE 0 END FROM USERS AS A) 
 SELECT Users.IDUsers, FIRSTNAME,LASTNAME,CHECKISADMIN,PROFESSINNAME FROM USERS
 INNER JOIN ISADMIN ON ISADMIN.IDUsers=USERS.IDUsers
 LEFT JOIN DOCTORS ON USERS.IDUsers=DOCTORS.IDDoctors
 LEFT JOIN PROFESSIONS ON IDPROFESSION=PROFESSIONS.IDProfessins
 WHERE CHECKISADMIN=@ISADMIN AND 
(CASE WHEN IDPROFESSION > 0 THEN 1 ELSE 0 END)=@ISADOCTOR
 ORDER BY FIRSTNAME,LASTNAME
 OFFSET ((@PAGENUMBER-1)*@COUNTINPAGE) ROWS 
 FETCH NEXT (@COUNTINPAGE) ROWS ONLY
 END;
 ELSE 
 BEGIN
 WITH ISADMIN(IDUsers,IDROLE,CHECKISADMIN)
 AS
(SELECT IDUsers,IDROLE, CASE WHEN IDROLE = 1 THEN 1 ELSE 0 END FROM USERS AS A) 
 SELECT Users.IDUsers, FIRSTNAME,LASTNAME,CHECKISADMIN,PROFESSINNAME FROM USERS
 INNER JOIN ISADMIN ON ISADMIN.IDUsers=USERS.IDUsers
 LEFT JOIN DOCTORS ON USERS.IDUsers=DOCTORS.IDDoctors
 LEFT JOIN PROFESSIONS ON IDPROFESSION=PROFESSIONS.IDProfessins
 WHERE (LASTNAME LIKE @FIRSTORLASTNAME+'%' OR FIRSTNAME LIKE @FIRSTORLASTNAME+'%') 
 AND CHECKISADMIN=@ISADMIN AND 
(CASE WHEN IDPROFESSION > 0 THEN 1 ELSE 0 END)=@ISADOCTOR
 ORDER BY FIRSTNAME,LASTNAME 
 OFFSET ((@PAGENUMBER-1)*@COUNTINPAGE) ROWS 
 FETCH NEXT (@COUNTINPAGE) ROWS ONLY
END;
