IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LOGGER')
BEGIN
	DROP TABLE LOGGER;
END

CREATE TABLE LOGGER(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
ROW_ID INT,
OLD NVARCHAR(20),
NEW NVARCHAR(20),
TABLE_NAME NVARCHAR(20),
COLUMN_NAME NVARCHAR(20),
DATE_OF_UPDATE DATETIME,
USER_ID INT)