IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'CHANGE_PASSWORD')
DROP PROC CHANGE_PASSWORD;

GO
CREATE PROCEDURE CHANGE_PASSWORD
	@EMAIL NVARCHAR(40), @PASSWORD NVARCHAR(70)
AS
BEGIN
	IF EXISTS (SELECT * FROM USERS WHERE EMAIL = @EMAIL)
		BEGIN
			BEGIN TRANSACTION;
				UPDATE USERS SET PASSWORD = @PASSWORD
				WHERE EMAIL = @EMAIL;
			COMMIT TRANSACTION;
		END;
END
