IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name ='LIST_USER_FOR_ROLE')
BEGIN
 DROP PROC LIST_USER_FOR_ROLE
END
GO
CREATE PROCEDURE LIST_USER_FOR_ROLE 
 @SEARCHTEXT NVARCHAR(30)
AS
BEGIN
SELECT FIRSTNAME,LASTNAME FROM USERS WHERE CONCAT(REPLACE(LASTNAME,' ', ''),REPLACE(FIRSTNAME,' ', '')) LIKE '%'+@SEARCHTEXT+'%' OR CONCAT(REPLACE(FIRSTNAME,' ', ''),REPLACE(LASTNAME,' ', '')) LIKE '%'+@SEARCHTEXT+'%'
END;
