IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name ='GET_DISEASE_INFO')
BEGIN
	DROP PROC GET_DISEASE_INFO
END

GO
CREATE PROCEDURE GET_DISEASE_INFO
	@ID_DISEASE INT, 
	@IDPATIENT INT 
AS
BEGIN
	SELECT USERS.FIRSTNAME, USERS.LASTNAME, SCHEDULE.START_DATETIME, MEDICAL_CARD.DESCRIPTION, MEDICAL_CARD.CURE
	FROM (PATIENT_DISEASES INNER JOIN SCHEDULE ON PATIENT_DISEASES.ID_VISIT = SCHEDULE.ID
							INNER JOIN MEDICAL_CARD ON PATIENT_DISEASES.ID_VISIT = MEDICAL_CARD.ID_VISIT
							INNER JOIN USERS on SCHEDULE.IDDOCTOR=USERS.IDUsers) 
	WHERE (ID_DISEASE = @ID_DISEASE AND IDPATIENT = @IDPATIENT AND PATIENT_DISEASES.END_DATETIME IS NULL)
END;