IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SET_CURRENT_USER')
BEGIN
	DROP PROC SET_CURRENT_USER
END

GO
CREATE PROCEDURE SET_CURRENT_USER
    @USER_ID INT
AS
BEGIN
    SET CONTEXT_INFO @USER_ID; 
END;