IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'IF_USER_EXISTS')
	DROP PROC IF_USER_EXISTS;

GO
CREATE PROCEDURE IF_USER_EXISTS
	@EMAIL NVARCHAR(40)
AS
BEGIN
	IF EXISTS (SELECT * FROM USERS WHERE EMAIL = @EMAIL)
		RETURN 1
	ELSE
		RETURN 0
END
