IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SET_CURRENT_USER')
	DROP PROC SET_CURRENT_USER
GO

CREATE PROCEDURE SET_CURRENT_USER
    @USER_ID INT
AS
BEGIN
IF (OBJECT_ID('USER_UPDATE', 'U') IS NOT NULL) DROP TABLE USER_UPDATE;
    CREATE TABLE USER_UPDATE(
	ID_USER INT PRIMARY KEY)
	INSERT INTO USER_UPDATE VALUES(@USER_ID)
END;
GO