IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name ='GET_ALL_USERS')
BEGIN
 DROP PROC GET_ALL_USERS
END
GO
CREATE PROCEDURE GET_ALL_USERS
@PAGENUMBER INT,@COUNTINPAGE INT
AS
BEGIN
BEGIN TRANSACTION;
WITH ISADMIN(IDUsers,IDROLE,A)
AS
(SELECT IDUsers,IDROLE, CASE WHEN IDROLE = 1 THEN 1 ELSE 0 END FROM USERS AS A) 
 SELECT FIRSTNAME,LASTNAME,ISADMIN.A,PROFESSINNAME FROM USERS
 INNER JOIN ISADMIN ON ISADMIN.IDUsers=USERS.IDUsers
 LEFT JOIN DOCTORS ON USERS.IDUsers=DOCTORS.IDDoctors
 LEFT JOIN PROFESSIONS ON IDPROFESSION=PROFESSIONS.IDProfessins
 ORDER BY FIRSTNAME,LASTNAME 
 OFFSET ((@PAGENUMBER-1)*@COUNTINPAGE) ROWS 
 FETCH NEXT (@COUNTINPAGE) ROWS ONLY
COMMIT TRANSACTION;
END;
