IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name ='GET_PAGINATION_COUNT')
BEGIN
 DROP PROC GET_PAGINATION_COUNT
END
GO
CREATE PROCEDURE GET_PAGINATION_COUNT
@COUNTINPAGE INT,@PAGINATION INT OUTPUT
AS
BEGIN
SET @PAGINATION=CEILING(CAST((SELECT COUNT(*) FROM USERS)/CAST(@COUNTINPAGE AS FLOAT)AS FLOAT))
END;
