IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name ='FILTERING_USERS')
BEGIN
 DROP PROC FILTERING_USERS
END
GO
CREATE PROCEDURE FILTERING_USERS
@FIRSTORLASTNAME NVARCHAR(30),@ISADMIN BIT,@ISADOCTOR BIT
AS
BEGIN
BEGIN TRANSACTION;
WITH ISADMIN(IDUsers,IDROLE,CHECKISADMIN)
AS
(SELECT IDUsers,IDROLE, CASE WHEN IDROLE = 1 THEN 1 ELSE 0 END FROM USERS AS A) 
 SELECT FIRSTNAME,LASTNAME,CHECKISADMIN,PROFESSINNAME FROM USERS
 INNER JOIN ISADMIN ON ISADMIN.IDUsers=USERS.IDUsers
 LEFT JOIN DOCTORS ON USERS.IDUsers=DOCTORS.IDDoctors
 LEFT JOIN PROFESSIONS ON IDPROFESSION=PROFESSIONS.IDProfessins
 WHERE (LASTNAME LIKE @FIRSTORLASTNAME+'%' OR FIRSTNAME LIKE @FIRSTORLASTNAME+'%') 
 AND CHECKISADMIN=0 AND 
(CASE WHEN IDPROFESSION > 0 THEN 1 ELSE 0 END)=@ISADOCTOR
 ORDER BY FIRSTNAME,LASTNAME 
COMMIT TRANSACTION;
END;
