IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_INFO_ABOUT_CLOSED_ALLERGIES')
DROP PROC GET_INFO_ABOUT_CLOSED_ALLERGIES;

GO
CREATE PROCEDURE GET_INFO_ABOUT_CLOSED_ALLERGIES
  @PATIENT_ID INT
AS
BEGIN
  SELECT ALLERGY_NAME, USERS1.FIRSTNAME AS DOCTOR_OPEN_FIRSTNAME, USERS1.LASTNAME AS DOCTOR_OPEN_LASTNAME, 
    SCHEDULE1.START_DATETIME, MEDICAL_CARD1.DESCRIPTION, MEDICAL_CARD1.CURE, 
    USERS2.FIRSTNAME AS DOCTOR_CLOSE_FIRSTNAME, USERS2.LASTNAME AS DOCTOR_CLOSE_LASTNAME, 
    SCHEDULE2.START_DATETIME AS END_TIME, MEDICAL_CARD2.DESCRIPTION, MEDICAL_CARD2.CURE
    FROM (USERS_ALLERGIES INNER JOIN SCHEDULE SCHEDULE1 ON USERS_ALLERGIES.ID_VISIT = SCHEDULE1.ID
      LEFT JOIN MEDICAL_CARD MEDICAL_CARD1 ON USERS_ALLERGIES.ID_VISIT = MEDICAL_CARD1.ID_VISIT 
      INNER JOIN USERS USERS1 on SCHEDULE1.IDDOCTOR=USERS1.IDUsers
      INNER JOIN SCHEDULE SCHEDULE2 ON USERS_ALLERGIES.END_DATETIME = SCHEDULE2.ID
      LEFT JOIN MEDICAL_CARD MEDICAL_CARD2 ON USERS_ALLERGIES.ID_VISIT = MEDICAL_CARD2.ID_VISIT
      INNER JOIN USERS USERS2 on SCHEDULE2.IDDOCTOR=USERS2.IDUsers
      INNER JOIN ALLERGIES ON ALLERGIES.ID_ALLERGY=USERS_ALLERGIES.ALLERGY_ID) 
    WHERE (SCHEDULE1.IDPATIENT = @PATIENT_ID AND USERS_ALLERGIES.END_DATETIME IS NOT NULL);
END;
